name: Build & Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake build-essential \
            libcli11-dev libdwarf-dev libelf-dev \
            libpfm4-dev libglfw3-dev libgl1-mesa-dev \
            rpm

      - name: Configure
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCACHESCOPE_BUILD_GUI=ON
          -DCACHESCOPE_BUILD_WORKLOADS=OFF
          -DBUILD_TESTING=OFF
          -DCACHESCOPE_ENABLE_PACKAGING=ON

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Generate Packages
        run: |
          cd build
          cpack -G DEB
          cpack -G RPM

      - name: List generated files
        run: ls -lh build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.deb
            build/*.rpm
